# Generated by Django 4.2.2 on 2023-06-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_alter_link_current_price_alter_link_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyModelName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "my_field_name",
                    models.CharField(
                        help_text="Enter field documentation", max_length=20
                    ),
                ),
            ],
            options={
                "ordering": ["-my_field_name"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("reg_number", models.CharField(max_length=13)),
                ("full_company_name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("head_name", models.CharField(max_length=60)),
                ("phone", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=50)),
                ("reg_date", models.DateField(max_length=50)),
                ("company_age", models.DecimalField(decimal_places=2, max_digits=6)),
                ("industry_type", models.CharField(max_length=254)),
                ("summary_indicator", models.CharField(max_length=15)),
                ("share_capital", models.DecimalField(decimal_places=2, max_digits=20)),
                ("sale_articles", models.CharField(max_length=254)),
                ("important_info", models.CharField(max_length=254)),
                ("product_supplier", models.CharField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name="Link",
        ),
    ]
